app = "absortech-api"
primary_region = "gru"

[build]
  dockerfile = "../../dockerfiles/django"

[env]
  DJANGO_SETTINGS_MODULE = "DjangoAbsortech.settings"
  DB_NAME = "AbsortechDB"
  DB_USER = "admin"
  DJANGO_DEBUG = "False"
  DJANGO_ALLOWED_HOSTS = "absortech.site"
  DB_PORT = "5432"

[http_service]
  internal_port = 8000
  force_https = true
  auto_start_machines = true
  auto_stop_machines = "off"
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
