app = "absortech-mqtt-worker"
primary_region = "gru"

[build]
  dockerfile = "../../dockerfiles/mqtt"

[processes]
  app = "python src/run.py"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
