# Generated by Django 5.1.3 on 2025-02-12 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispenser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('localizacao', models.CharField(max_length=255)),
                ('instituicao', models.CharField(max_length=100)),
                ('bloco', models.CharField(max_length=50)),
                ('andar', models.IntegerField()),
                ('ativo', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeituraSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('distancia_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('quantidade_estimada', models.IntegerField(blank=True, null=True)),
                ('porcentagem_ocupacao', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dispenser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to='app.dispenser')),
            ],
        ),
    ]
