import re
from datetime import datetime
from decimal import Decimal, ROUND_FLOOR

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Q
from django.utils import timezone


DISTANCIA_CHEIO_CM = Decimal('2.00')
DISTANCIA_VAZIO_CM = Decimal('30.00')
CAPACIDADE_MAXIMA = 20


def _calcular_dados_processados(distancia):
    distancia = Decimal(str(distancia))
    distancia_limitada = min(
        max(distancia, DISTANCIA_CHEIO_CM),
        DISTANCIA_VAZIO_CM
    )
    porcentagem = (
        (DISTANCIA_VAZIO_CM - distancia_limitada)
        / (DISTANCIA_VAZIO_CM - DISTANCIA_CHEIO_CM)
        * Decimal('100')
    )
    porcentagem = porcentagem.quantize(Decimal('0.01'))
    quantidade = int(
        (
            porcentagem
            / Decimal('100')
            * CAPACIDADE_MAXIMA
        ).to_integral_value(rounding=ROUND_FLOOR)
    )
    return quantidade, porcentagem


def _numero_andar(valor):
    match = re.search(r'-?\d+', str(valor))
    return int(match.group()) if match else 0


def _colunas(schema_editor, tabela):
    with schema_editor.connection.cursor() as cursor:
        descricao = schema_editor.connection.introspection.get_table_description(
            cursor,
            tabela
        )
    return {coluna.name for coluna in descricao}


def atualizar_schema_legado(apps, schema_editor):
    tabelas = set(schema_editor.connection.introspection.table_names())

    if 'app_dispenser' not in tabelas:
        schema_editor.execute(
            """
            CREATE TABLE app_dispenser (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                nome varchar(100) NOT NULL,
                localizacao varchar(255) NOT NULL,
                instituicao varchar(100) NOT NULL,
                bloco varchar(50) NOT NULL,
                andar integer NOT NULL,
                ativo boolean NOT NULL DEFAULT TRUE,
                created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
            """
        )

    colunas = _colunas(schema_editor, 'app_leiturasensor')
    novas_colunas = {
        'timestamp': 'timestamp with time zone',
        'distancia_cm': 'numeric(6, 2)',
        'quantidade_estimada': 'integer',
        'porcentagem_ocupacao': 'numeric(5, 2)',
        'dispenser_id': 'bigint'
    }
    for nome, tipo in novas_colunas.items():
        if nome not in colunas:
            schema_editor.execute(
                f'ALTER TABLE app_leiturasensor ADD COLUMN {nome} {tipo}'
            )

    colunas = _colunas(schema_editor, 'app_leiturasensor')
    colunas_legadas = {'andar', 'data', 'hora', 'valor_leitura'}
    if colunas_legadas.issubset(colunas):
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                """
                SELECT id, andar, data, hora, valor_leitura
                FROM app_leiturasensor
                ORDER BY id
                """
            )
            leituras_legadas = cursor.fetchall()

        dispensers = {}
        for leitura_id, andar_original, data, hora, valor in leituras_legadas:
            chave = str(andar_original).strip().casefold() or 'nao informado'
            dispenser_id = dispensers.get(chave)
            if dispenser_id is None:
                andar = _numero_andar(andar_original)
                with schema_editor.connection.cursor() as cursor:
                    cursor.execute(
                        """
                        INSERT INTO app_dispenser
                            (nome, localizacao, instituicao, bloco, andar, ativo, created_at)
                        VALUES (%s, %s, %s, %s, %s, TRUE, CURRENT_TIMESTAMP)
                        RETURNING id
                        """,
                        [
                            f'Dispenser legado - {andar_original}',
                            f'Andar {andar_original}',
                            'Nao informada',
                            'Nao informado',
                            andar
                        ],
                    )
                    dispenser_id = cursor.fetchone()[0]
                dispensers[chave] = dispenser_id

            timestamp = datetime.combine(data, hora)
            if timezone.is_naive(timestamp):
                timestamp = timezone.make_aware(timestamp, timezone.get_default_timezone())
            quantidade, porcentagem = _calcular_dados_processados(valor)

            with schema_editor.connection.cursor() as cursor:
                cursor.execute(
                    """
                    UPDATE app_leiturasensor
                    SET timestamp = %s,
                        distancia_cm = %s,
                        quantidade_estimada = %s,
                        porcentagem_ocupacao = %s,
                        dispenser_id = %s
                    WHERE id = %s
                    """,
                    [
                        timestamp,
                        valor,
                        quantidade,
                        porcentagem,
                        dispenser_id,
                        leitura_id
                    ],
                )

        for coluna in colunas_legadas:
            schema_editor.execute(
                f'ALTER TABLE app_leiturasensor DROP COLUMN IF EXISTS {coluna}'
            )

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            'SELECT COUNT(*) FROM app_leiturasensor WHERE dispenser_id IS NULL'
        )
        leituras_sem_dispenser = cursor.fetchone()[0]

    if leituras_sem_dispenser:
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                """
                INSERT INTO app_dispenser
                    (nome, localizacao, instituicao, bloco, andar, ativo, created_at)
                VALUES (%s, %s, %s, %s, %s, TRUE, CURRENT_TIMESTAMP)
                RETURNING id
                """,
                [
                    'Dispenser legado sem identificacao',
                    'Nao informada',
                    'Nao informada',
                    'Nao informado',
                    0
                ],
            )
            dispenser_id = cursor.fetchone()[0]
            cursor.execute(
                """
                UPDATE app_leiturasensor
                SET dispenser_id = %s
                WHERE dispenser_id IS NULL
                """,
                [dispenser_id]
            )

    schema_editor.execute(
        """
        UPDATE app_leiturasensor
        SET timestamp = CURRENT_TIMESTAMP
        WHERE timestamp IS NULL
        """
    )
    schema_editor.execute(
        'ALTER TABLE app_leiturasensor ALTER COLUMN timestamp SET NOT NULL'
    )
    schema_editor.execute(
        'ALTER TABLE app_leiturasensor ALTER COLUMN dispenser_id SET NOT NULL'
    )
    schema_editor.execute(
        """
        CREATE INDEX IF NOT EXISTS app_leiturasensor_dispenser_id_idx
        ON app_leiturasensor (dispenser_id)
        """
    )
    schema_editor.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1
                FROM pg_constraint
                WHERE conrelid = 'app_leiturasensor'::regclass
                  AND confrelid = 'app_dispenser'::regclass
                  AND contype = 'f'
            ) THEN
                ALTER TABLE app_leiturasensor
                ADD CONSTRAINT app_leiturasensor_dispenser_id_fk
                FOREIGN KEY (dispenser_id)
                REFERENCES app_dispenser (id)
                DEFERRABLE INITIALLY DEFERRED;
            END IF;
        END
        $$;
        """
    )


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0001_initial')
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    atualizar_schema_legado,
                )
            ],
            state_operations=[
                migrations.CreateModel(
                    name='Dispenser',
                    fields=[
                        (
                            'id',
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name='ID'
                            )
                        ),
                        ('nome', models.CharField(max_length=100)),
                        ('localizacao', models.CharField(max_length=255)),
                        ('instituicao', models.CharField(max_length=100)),
                        ('bloco', models.CharField(max_length=50)),
                        ('andar', models.IntegerField()),
                        ('ativo', models.BooleanField(default=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True))
                    ],
                    options={
                        'ordering': ['instituicao', 'bloco', 'andar', 'nome']
                    }
                ),
                migrations.AddField(
                    model_name='leiturasensor',
                    name='timestamp',
                    field=models.DateTimeField(default=timezone.now)
                ),
                migrations.AddField(
                    model_name='leiturasensor',
                    name='distancia_cm',
                    field=models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal('0'))
                        ]
                    )
                ),
                migrations.AddField(
                    model_name='leiturasensor',
                    name='quantidade_estimada',
                    field=models.IntegerField(
                        blank=True,
                        editable=False,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)]
                    )
                ),
                migrations.AddField(
                    model_name='leiturasensor',
                    name='porcentagem_ocupacao',
                    field=models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        editable=False,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal('0')),
                            django.core.validators.MaxValueValidator(Decimal('100'))
                        ]
                    )
                ),
                migrations.AddField(
                    model_name='leiturasensor',
                    name='dispenser',
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='leituras',
                        to='app.dispenser'
                    )
                ),
                migrations.RemoveField(
                    model_name='leiturasensor',
                    name='andar'
                ),
                migrations.RemoveField(
                    model_name='leiturasensor',
                    name='data'
                ),
                migrations.RemoveField(
                    model_name='leiturasensor',
                    name='hora'
                ),
                migrations.RemoveField(
                    model_name='leiturasensor',
                    name='valor_leitura'
                ),
                migrations.AlterModelOptions(
                    name='leiturasensor',
                    options={'ordering': ['-timestamp', '-id']}
                )
            ],
        ),
        migrations.AddIndex(
            model_name='dispenser',
            index=models.Index(
                fields=['instituicao', 'bloco', 'andar'],
                name='dispenser_location_idx'
            )
        ),
        migrations.AddIndex(
            model_name='leiturasensor',
            index=models.Index(
                fields=['timestamp'],
                name='leitura_timestamp_idx'
            )
        ),
        migrations.AddIndex(
            model_name='leiturasensor',
            index=models.Index(
                fields=['dispenser', '-timestamp'],
                name='leitura_disp_ts_idx'
            )
        ),
        migrations.AddConstraint(
            model_name='leiturasensor',
            constraint=models.CheckConstraint(
                condition=Q(distancia_cm__gte=0),
                name='leitura_distancia_nonneg'
            )
        ),
        migrations.AddConstraint(
            model_name='leiturasensor',
            constraint=models.CheckConstraint(
                condition=Q(quantidade_estimada__isnull=True)
                | Q(quantidade_estimada__gte=0),
                name='leitura_quantidade_nonneg'
            )
        ),
        migrations.AddConstraint(
            model_name='leiturasensor',
            constraint=models.CheckConstraint(
                condition=Q(porcentagem_ocupacao__isnull=True)
                | Q(
                    porcentagem_ocupacao__gte=0,
                    porcentagem_ocupacao__lte=100
                ),
                name='leitura_ocupacao_range'
            )
        )
    ]
